### ISSUE TITLE
Migrate `TriWheels` API

### ISSUE THREAD

**Issue by BD103** [BotsBurgh/BOTSBURGH-FTC-2024-25#9]
[`TriWheels`] is one of the most useful APIs from last year, enabling use of the 3 wheels on a Kiwi drive. It should be copied over, and improved if possible, for this year.

[`TriWheels`]: https://github.com/BotsBurgh/BOTSBURGH-FTC-2023-24/blob/457483751af7fa941e585ce53c3079d9ef7ac94f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt

**Comment by SnipSnek** [comment]
added some files with TriWheels to make it work correctly
